### ISSUE TITLE
INvalid Captcha

### ISSUE THREAD

**Issue by snipymc** [BkrBkr/AuthCaptchaForJoomla#1]
Hey,

just installed the plugin on my Joomla with version 3.9.10
By trying to login on loginform I will get the error "Invalid Captcha" while the captcha is correct.

**Comment by BkrBkr** [comment]
Unfortunately, I was very busy in my private life this year, so your request was lost. I'm sorry about that. Is there still a need for support?

**Comment by filterVERLAG** [comment]
Hey, just installed it and made the setup for admin login / Captcha is solved but I´m getting "Invalid Captcha". Latest Joomla! 4.4.8 and latest codes from here. What´s next? I disabled it for now.
